# Generated by Django 4.2.1 on 2023-06-01 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=50, verbose_name='наименование категории')),
                ('category_desc', models.CharField(blank=True, max_length=250, null=True, verbose_name='описание')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('products_name', models.CharField(max_length=100, verbose_name='имя продукта')),
                ('description', models.CharField(blank=True, max_length=500, null=True, verbose_name='описание')),
                ('product_image', models.ImageField(blank=True, null=True, upload_to='prod_images/', verbose_name='изображение')),
                ('category', models.CharField(max_length=100, verbose_name='категория')),
                ('price_per_purchase', models.IntegerField(verbose_name='цена за покупку')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='дата создания')),
                ('last_time_modified', models.DateTimeField(auto_now=True, verbose_name='дата последнего изменения')),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Продукты',
            },
        ),
    ]
